spring.application.name=asset_mgmt

#H2 config in-memory db. exist when application run
spring.datasource.url=jdbc:h2:mem:testdb

#Hibernate / JPA
spring.jpa.show-sql=true
#Auto create / update tables
spring.jpa.hibernate.ddl-auto=update

#H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console